/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionSetup -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "EPDCCH-SetConfig-r11.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_resourceBlockAssignment_r11_constraint_6(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size >= 4UL && size <= 38UL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_dmrs_ScramblingSequenceInt_r11_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 503L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pucch_ResourceStartOffset_r11_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 2047L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_transmissionType_r11_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_numberPRB_Pairs_r11_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_resourceBlockAssignment_r11_constr_11 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  4,  38 }	/* (SIZE(4..38)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_dmrs_ScramblingSequenceInt_r11_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  503 }	/* (0..503) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_pucch_ResourceStartOffset_r11_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 11,  11,  0,  2047 }	/* (0..2047) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_transmissionType_r11_value2enum_3[] = {
	{ 0,	9,	"localised" },
	{ 1,	11,	"distributed" }
};
static const unsigned int asn_MAP_transmissionType_r11_enum2value_3[] = {
	1,	/* distributed(1) */
	0	/* localised(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_transmissionType_r11_specs_3 = {
	asn_MAP_transmissionType_r11_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_transmissionType_r11_enum2value_3,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_transmissionType_r11_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_transmissionType_r11_3 = {
	"transmissionType-r11",
	"transmissionType-r11",
	&asn_OP_NativeEnumerated,
	asn_DEF_transmissionType_r11_tags_3,
	sizeof(asn_DEF_transmissionType_r11_tags_3)
		/sizeof(asn_DEF_transmissionType_r11_tags_3[0]) - 1, /* 1 */
	asn_DEF_transmissionType_r11_tags_3,	/* Same as above */
	sizeof(asn_DEF_transmissionType_r11_tags_3)
		/sizeof(asn_DEF_transmissionType_r11_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_transmissionType_r11_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_transmissionType_r11_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_numberPRB_Pairs_r11_value2enum_7[] = {
	{ 0,	2,	"n2" },
	{ 1,	2,	"n4" },
	{ 2,	2,	"n8" }
};
static const unsigned int asn_MAP_numberPRB_Pairs_r11_enum2value_7[] = {
	0,	/* n2(0) */
	1,	/* n4(1) */
	2	/* n8(2) */
};
static const asn_INTEGER_specifics_t asn_SPC_numberPRB_Pairs_r11_specs_7 = {
	asn_MAP_numberPRB_Pairs_r11_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_numberPRB_Pairs_r11_enum2value_7,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_numberPRB_Pairs_r11_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_numberPRB_Pairs_r11_7 = {
	"numberPRB-Pairs-r11",
	"numberPRB-Pairs-r11",
	&asn_OP_NativeEnumerated,
	asn_DEF_numberPRB_Pairs_r11_tags_7,
	sizeof(asn_DEF_numberPRB_Pairs_r11_tags_7)
		/sizeof(asn_DEF_numberPRB_Pairs_r11_tags_7[0]) - 1, /* 1 */
	asn_DEF_numberPRB_Pairs_r11_tags_7,	/* Same as above */
	sizeof(asn_DEF_numberPRB_Pairs_r11_tags_7)
		/sizeof(asn_DEF_numberPRB_Pairs_r11_tags_7[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_numberPRB_Pairs_r11_constr_7,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_numberPRB_Pairs_r11_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_resourceBlockAssignment_r11_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__resourceBlockAssignment_r11, numberPRB_Pairs_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_numberPRB_Pairs_r11_7,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"numberPRB-Pairs-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11__resourceBlockAssignment_r11, resourceBlockAssignment_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_resourceBlockAssignment_r11_constr_11,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_resourceBlockAssignment_r11_constraint_6
		},
		0, 0, /* No default value */
		"resourceBlockAssignment-r11"
		},
};
static const ber_tlv_tag_t asn_DEF_resourceBlockAssignment_r11_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_resourceBlockAssignment_r11_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* numberPRB-Pairs-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* resourceBlockAssignment-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_resourceBlockAssignment_r11_specs_6 = {
	sizeof(struct EPDCCH_SetConfig_r11__resourceBlockAssignment_r11),
	offsetof(struct EPDCCH_SetConfig_r11__resourceBlockAssignment_r11, _asn_ctx),
	asn_MAP_resourceBlockAssignment_r11_tag2el_6,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_resourceBlockAssignment_r11_6 = {
	"resourceBlockAssignment-r11",
	"resourceBlockAssignment-r11",
	&asn_OP_SEQUENCE,
	asn_DEF_resourceBlockAssignment_r11_tags_6,
	sizeof(asn_DEF_resourceBlockAssignment_r11_tags_6)
		/sizeof(asn_DEF_resourceBlockAssignment_r11_tags_6[0]) - 1, /* 1 */
	asn_DEF_resourceBlockAssignment_r11_tags_6,	/* Same as above */
	sizeof(asn_DEF_resourceBlockAssignment_r11_tags_6)
		/sizeof(asn_DEF_resourceBlockAssignment_r11_tags_6[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_resourceBlockAssignment_r11_6,
	2,	/* Elements count */
	&asn_SPC_resourceBlockAssignment_r11_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_EPDCCH_SetConfig_r11_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11, setConfigId_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EPDCCH_SetConfigId_r11,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"setConfigId-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11, transmissionType_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_transmissionType_r11_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"transmissionType-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11, resourceBlockAssignment_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_resourceBlockAssignment_r11_6,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"resourceBlockAssignment-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11, dmrs_ScramblingSequenceInt_r11),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_dmrs_ScramblingSequenceInt_r11_constr_12,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_dmrs_ScramblingSequenceInt_r11_constraint_1
		},
		0, 0, /* No default value */
		"dmrs-ScramblingSequenceInt-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EPDCCH_SetConfig_r11, pucch_ResourceStartOffset_r11),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_pucch_ResourceStartOffset_r11_constr_13,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_pucch_ResourceStartOffset_r11_constraint_1
		},
		0, 0, /* No default value */
		"pucch-ResourceStartOffset-r11"
		},
	{ ATF_POINTER, 1, offsetof(struct EPDCCH_SetConfig_r11, re_MappingQCL_ConfigId_r11),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_RE_MappingQCL_ConfigId_r11,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"re-MappingQCL-ConfigId-r11"
		},
};
static const int asn_MAP_EPDCCH_SetConfig_r11_oms_1[] = { 5 };
static const ber_tlv_tag_t asn_DEF_EPDCCH_SetConfig_r11_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EPDCCH_SetConfig_r11_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* setConfigId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* transmissionType-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* resourceBlockAssignment-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dmrs-ScramblingSequenceInt-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* pucch-ResourceStartOffset-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* re-MappingQCL-ConfigId-r11 */
};
asn_SEQUENCE_specifics_t asn_SPC_EPDCCH_SetConfig_r11_specs_1 = {
	sizeof(struct EPDCCH_SetConfig_r11),
	offsetof(struct EPDCCH_SetConfig_r11, _asn_ctx),
	asn_MAP_EPDCCH_SetConfig_r11_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_EPDCCH_SetConfig_r11_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EPDCCH_SetConfig_r11 = {
	"EPDCCH-SetConfig-r11",
	"EPDCCH-SetConfig-r11",
	&asn_OP_SEQUENCE,
	asn_DEF_EPDCCH_SetConfig_r11_tags_1,
	sizeof(asn_DEF_EPDCCH_SetConfig_r11_tags_1)
		/sizeof(asn_DEF_EPDCCH_SetConfig_r11_tags_1[0]), /* 1 */
	asn_DEF_EPDCCH_SetConfig_r11_tags_1,	/* Same as above */
	sizeof(asn_DEF_EPDCCH_SetConfig_r11_tags_1)
		/sizeof(asn_DEF_EPDCCH_SetConfig_r11_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_EPDCCH_SetConfig_r11_1,
	6,	/* Elements count */
	&asn_SPC_EPDCCH_SetConfig_r11_specs_1	/* Additional specs */
};

