/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_CSI_Process_r11_H_
#define	_CSI_Process_r11_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CSI-ProcessId-r11.h"
#include "CSI-RS-ConfigNZPId-r11.h"
#include "CSI-IM-ConfigId-r11.h"
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CQI_ReportBothProc_r11;
struct CQI_ReportAperiodicProc_r11;
struct P_C_AndCBSR_r11;

/* CSI-Process-r11 */
typedef struct CSI_Process_r11 {
	CSI_ProcessId_r11_t	 csi_ProcessId_r11;
	CSI_RS_ConfigNZPId_r11_t	 csi_RS_ConfigNZPId_r11;
	CSI_IM_ConfigId_r11_t	 csi_IM_ConfigId_r11;
	struct CSI_Process_r11__p_C_AndCBSRList_r11 {
		A_SEQUENCE_OF(struct P_C_AndCBSR_r11) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} p_C_AndCBSRList_r11;
	struct CQI_ReportBothProc_r11	*cqi_ReportBothProc_r11;	/* OPTIONAL */
	long	*cqi_ReportPeriodicProcId_r11;	/* OPTIONAL */
	struct CQI_ReportAperiodicProc_r11	*cqi_ReportAperiodicProc_r11;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSI_Process_r11_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSI_Process_r11;
extern asn_SEQUENCE_specifics_t asn_SPC_CSI_Process_r11_specs_1;
extern asn_TYPE_member_t asn_MBR_CSI_Process_r11_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _CSI_Process_r11_H_ */
#include <asn_internal.h>
