/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_PhysicalConfigDedicatedSCell_r10_H_
#define	_PhysicalConfigDedicatedSCell_r10_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AntennaInfoDedicated_r10;
struct CrossCarrierSchedulingConfig_r10;
struct CSI_RS_Config_r10;
struct PDSCH_ConfigDedicated;
struct AntennaInfoUL_r10;
struct PUSCH_ConfigDedicatedSCell_r10;
struct UplinkPowerControlDedicatedSCell_r10;
struct CQI_ReportConfigSCell_r10;
struct SoundingRS_UL_ConfigDedicated;
struct SoundingRS_UL_ConfigDedicated_v1020;
struct SoundingRS_UL_ConfigDedicatedAperiodic_r10;
struct CSI_RS_ConfigNZPToReleaseList_r11;
struct CSI_RS_ConfigNZPToAddModList_r11;
struct CSI_RS_ConfigZPToReleaseList_r11;
struct CSI_RS_ConfigZPToAddModList_r11;
struct EPDCCH_Config_r11;
struct PDSCH_ConfigDedicated_v1130;
struct CQI_ReportConfig_v1130;
struct PUSCH_ConfigDedicated_v1130;
struct UplinkPowerControlDedicated_v1130;

/* PhysicalConfigDedicatedSCell-r10 */
typedef struct PhysicalConfigDedicatedSCell_r10 {
	struct PhysicalConfigDedicatedSCell_r10__nonUL_Configuration_r10 {
		struct AntennaInfoDedicated_r10	*antennaInfo_r10;	/* OPTIONAL */
		struct CrossCarrierSchedulingConfig_r10	*crossCarrierSchedulingConfig_r10;	/* OPTIONAL */
		struct CSI_RS_Config_r10	*csi_RS_Config_r10;	/* OPTIONAL */
		struct PDSCH_ConfigDedicated	*pdsch_ConfigDedicated_r10;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonUL_Configuration_r10;
	struct PhysicalConfigDedicatedSCell_r10__ul_Configuration_r10 {
		struct AntennaInfoUL_r10	*antennaInfoUL_r10;	/* OPTIONAL */
		struct PUSCH_ConfigDedicatedSCell_r10	*pusch_ConfigDedicatedSCell_r10;	/* OPTIONAL */
		struct UplinkPowerControlDedicatedSCell_r10	*uplinkPowerControlDedicatedSCell_r10;	/* OPTIONAL */
		struct CQI_ReportConfigSCell_r10	*cqi_ReportConfigSCell_r10;	/* OPTIONAL */
		struct SoundingRS_UL_ConfigDedicated	*soundingRS_UL_ConfigDedicated_r10;	/* OPTIONAL */
		struct SoundingRS_UL_ConfigDedicated_v1020	*soundingRS_UL_ConfigDedicated_v1020;	/* OPTIONAL */
		struct SoundingRS_UL_ConfigDedicatedAperiodic_r10	*soundingRS_UL_ConfigDedicatedAperiodic_r10;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ul_Configuration_r10;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct PhysicalConfigDedicatedSCell_r10__ext1 {
		struct CSI_RS_ConfigNZPToReleaseList_r11	*csi_RS_ConfigNZPToReleaseList_r11;	/* OPTIONAL */
		struct CSI_RS_ConfigNZPToAddModList_r11	*csi_RS_ConfigNZPToAddModList_r11;	/* OPTIONAL */
		struct CSI_RS_ConfigZPToReleaseList_r11	*csi_RS_ConfigZPToReleaseList_r11;	/* OPTIONAL */
		struct CSI_RS_ConfigZPToAddModList_r11	*csi_RS_ConfigZPToAddModList_r11;	/* OPTIONAL */
		struct EPDCCH_Config_r11	*epdcch_Config_r11;	/* OPTIONAL */
		struct PDSCH_ConfigDedicated_v1130	*pdsch_ConfigDedicated_v1130;	/* OPTIONAL */
		struct CQI_ReportConfig_v1130	*cqi_ReportConfig_v1130;	/* OPTIONAL */
		struct PUSCH_ConfigDedicated_v1130	*pusch_ConfigDedicated_v1130;	/* OPTIONAL */
		struct UplinkPowerControlDedicated_v1130	*uplinkPowerControlDedicatedSCell_v1130;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PhysicalConfigDedicatedSCell_r10_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysicalConfigDedicatedSCell_r10;
extern asn_SEQUENCE_specifics_t asn_SPC_PhysicalConfigDedicatedSCell_r10_specs_1;
extern asn_TYPE_member_t asn_MBR_PhysicalConfigDedicatedSCell_r10_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PhysicalConfigDedicatedSCell_r10_H_ */
#include <asn_internal.h>
