/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_RadioResourceConfigCommonSIB_H_
#define	_RadioResourceConfigCommonSIB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RACH-ConfigCommon.h"
#include "BCCH-Config.h"
#include "PCCH-Config.h"
#include "PRACH-ConfigSIB.h"
#include "PDSCH-ConfigCommon.h"
#include "PUSCH-ConfigCommon.h"
#include "PUCCH-ConfigCommon.h"
#include "SoundingRS-UL-ConfigCommon.h"
#include "UplinkPowerControlCommon.h"
#include "UL-CyclicPrefixLength.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UplinkPowerControlCommon_v1020;

/* RadioResourceConfigCommonSIB */
typedef struct RadioResourceConfigCommonSIB {
	RACH_ConfigCommon_t	 rach_ConfigCommon;
	BCCH_Config_t	 bcch_Config;
	PCCH_Config_t	 pcch_Config;
	PRACH_ConfigSIB_t	 prach_Config;
	PDSCH_ConfigCommon_t	 pdsch_ConfigCommon;
	PUSCH_ConfigCommon_t	 pusch_ConfigCommon;
	PUCCH_ConfigCommon_t	 pucch_ConfigCommon;
	SoundingRS_UL_ConfigCommon_t	 soundingRS_UL_ConfigCommon;
	UplinkPowerControlCommon_t	 uplinkPowerControlCommon;
	UL_CyclicPrefixLength_t	 ul_CyclicPrefixLength;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct RadioResourceConfigCommonSIB__ext1 {
		struct UplinkPowerControlCommon_v1020	*uplinkPowerControlCommon_v1020;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadioResourceConfigCommonSIB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioResourceConfigCommonSIB;
extern asn_SEQUENCE_specifics_t asn_SPC_RadioResourceConfigCommonSIB_specs_1;
extern asn_TYPE_member_t asn_MBR_RadioResourceConfigCommonSIB_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _RadioResourceConfigCommonSIB_H_ */
#include <asn_internal.h>
