/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "RLF-Report-r9.h"

#include "MeasResultList2EUTRA-r9.h"
#include "MeasResultList2UTRA-r9.h"
#include "MeasResultListGERAN.h"
#include "MeasResultList2CDMA2000-r9.h"
#include "LocationInfo-r10.h"
#include "CellGlobalIdEUTRA.h"
#include "CellGlobalIdUTRA.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_timeConnFailure_r10_constraint_11(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 1023L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_failedPCellId_r10_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_connectionFailureType_r10_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_timeConnFailure_r10_constr_19 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 10,  10,  0,  1023 }	/* (0..1023) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_rlf_Cause_r11_constr_30 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_physCellId_r11_constr_38 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_physCellId_r11_constr_44 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_measResultLastServCell_r9_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__measResultLastServCell_r9, rsrpResult_r9),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRP_Range,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"rsrpResult-r9"
		},
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9__measResultLastServCell_r9, rsrqResult_r9),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRQ_Range,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"rsrqResult-r9"
		},
};
static const int asn_MAP_measResultLastServCell_r9_oms_2[] = { 1 };
static const ber_tlv_tag_t asn_DEF_measResultLastServCell_r9_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_measResultLastServCell_r9_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rsrpResult-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rsrqResult-r9 */
};
static asn_SEQUENCE_specifics_t asn_SPC_measResultLastServCell_r9_specs_2 = {
	sizeof(struct RLF_Report_r9__measResultLastServCell_r9),
	offsetof(struct RLF_Report_r9__measResultLastServCell_r9, _asn_ctx),
	asn_MAP_measResultLastServCell_r9_tag2el_2,
	2,	/* Count of tags in the map */
	asn_MAP_measResultLastServCell_r9_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResultLastServCell_r9_2 = {
	"measResultLastServCell-r9",
	"measResultLastServCell-r9",
	&asn_OP_SEQUENCE,
	asn_DEF_measResultLastServCell_r9_tags_2,
	sizeof(asn_DEF_measResultLastServCell_r9_tags_2)
		/sizeof(asn_DEF_measResultLastServCell_r9_tags_2[0]) - 1, /* 1 */
	asn_DEF_measResultLastServCell_r9_tags_2,	/* Same as above */
	sizeof(asn_DEF_measResultLastServCell_r9_tags_2)
		/sizeof(asn_DEF_measResultLastServCell_r9_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_measResultLastServCell_r9_2,
	2,	/* Elements count */
	&asn_SPC_measResultLastServCell_r9_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measResultNeighCells_r9_5[] = {
	{ ATF_POINTER, 4, offsetof(struct RLF_Report_r9__measResultNeighCells_r9, measResultListEUTRA_r9),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultList2EUTRA_r9,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"measResultListEUTRA-r9"
		},
	{ ATF_POINTER, 3, offsetof(struct RLF_Report_r9__measResultNeighCells_r9, measResultListUTRA_r9),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultList2UTRA_r9,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"measResultListUTRA-r9"
		},
	{ ATF_POINTER, 2, offsetof(struct RLF_Report_r9__measResultNeighCells_r9, measResultListGERAN_r9),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultListGERAN,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"measResultListGERAN-r9"
		},
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9__measResultNeighCells_r9, measResultsCDMA2000_r9),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultList2CDMA2000_r9,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"measResultsCDMA2000-r9"
		},
};
static const int asn_MAP_measResultNeighCells_r9_oms_5[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_measResultNeighCells_r9_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_measResultNeighCells_r9_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measResultListEUTRA-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measResultListUTRA-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* measResultListGERAN-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* measResultsCDMA2000-r9 */
};
static asn_SEQUENCE_specifics_t asn_SPC_measResultNeighCells_r9_specs_5 = {
	sizeof(struct RLF_Report_r9__measResultNeighCells_r9),
	offsetof(struct RLF_Report_r9__measResultNeighCells_r9, _asn_ctx),
	asn_MAP_measResultNeighCells_r9_tag2el_5,
	4,	/* Count of tags in the map */
	asn_MAP_measResultNeighCells_r9_oms_5,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResultNeighCells_r9_5 = {
	"measResultNeighCells-r9",
	"measResultNeighCells-r9",
	&asn_OP_SEQUENCE,
	asn_DEF_measResultNeighCells_r9_tags_5,
	sizeof(asn_DEF_measResultNeighCells_r9_tags_5)
		/sizeof(asn_DEF_measResultNeighCells_r9_tags_5[0]) - 1, /* 1 */
	asn_DEF_measResultNeighCells_r9_tags_5,	/* Same as above */
	sizeof(asn_DEF_measResultNeighCells_r9_tags_5)
		/sizeof(asn_DEF_measResultNeighCells_r9_tags_5[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_measResultNeighCells_r9_5,
	4,	/* Elements count */
	&asn_SPC_measResultNeighCells_r9_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_pci_arfcn_r10_15[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext1__failedPCellId_r10__pci_arfcn_r10, physCellId_r10),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellId,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"physCellId-r10"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext1__failedPCellId_r10__pci_arfcn_r10, carrierFreq_r10),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueEUTRA,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"carrierFreq-r10"
		},
};
static const ber_tlv_tag_t asn_DEF_pci_arfcn_r10_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_pci_arfcn_r10_tag2el_15[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* physCellId-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* carrierFreq-r10 */
};
static asn_SEQUENCE_specifics_t asn_SPC_pci_arfcn_r10_specs_15 = {
	sizeof(struct RLF_Report_r9__ext1__failedPCellId_r10__pci_arfcn_r10),
	offsetof(struct RLF_Report_r9__ext1__failedPCellId_r10__pci_arfcn_r10, _asn_ctx),
	asn_MAP_pci_arfcn_r10_tag2el_15,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pci_arfcn_r10_15 = {
	"pci-arfcn-r10",
	"pci-arfcn-r10",
	&asn_OP_SEQUENCE,
	asn_DEF_pci_arfcn_r10_tags_15,
	sizeof(asn_DEF_pci_arfcn_r10_tags_15)
		/sizeof(asn_DEF_pci_arfcn_r10_tags_15[0]) - 1, /* 1 */
	asn_DEF_pci_arfcn_r10_tags_15,	/* Same as above */
	sizeof(asn_DEF_pci_arfcn_r10_tags_15)
		/sizeof(asn_DEF_pci_arfcn_r10_tags_15[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_pci_arfcn_r10_15,
	2,	/* Elements count */
	&asn_SPC_pci_arfcn_r10_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_failedPCellId_r10_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext1__failedPCellId_r10, choice.cellGlobalId_r10),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdEUTRA,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"cellGlobalId-r10"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext1__failedPCellId_r10, choice.pci_arfcn_r10),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_pci_arfcn_r10_15,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"pci-arfcn-r10"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_failedPCellId_r10_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellGlobalId-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* pci-arfcn-r10 */
};
static asn_CHOICE_specifics_t asn_SPC_failedPCellId_r10_specs_13 = {
	sizeof(struct RLF_Report_r9__ext1__failedPCellId_r10),
	offsetof(struct RLF_Report_r9__ext1__failedPCellId_r10, _asn_ctx),
	offsetof(struct RLF_Report_r9__ext1__failedPCellId_r10, present),
	sizeof(((struct RLF_Report_r9__ext1__failedPCellId_r10 *)0)->present),
	asn_MAP_failedPCellId_r10_tag2el_13,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_failedPCellId_r10_13 = {
	"failedPCellId-r10",
	"failedPCellId-r10",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_failedPCellId_r10_constr_13,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_failedPCellId_r10_13,
	2,	/* Elements count */
	&asn_SPC_failedPCellId_r10_specs_13	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_connectionFailureType_r10_value2enum_20[] = {
	{ 0,	3,	"rlf" },
	{ 1,	3,	"hof" }
};
static const unsigned int asn_MAP_connectionFailureType_r10_enum2value_20[] = {
	1,	/* hof(1) */
	0	/* rlf(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_connectionFailureType_r10_specs_20 = {
	asn_MAP_connectionFailureType_r10_value2enum_20,	/* "tag" => N; sorted by tag */
	asn_MAP_connectionFailureType_r10_enum2value_20,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_connectionFailureType_r10_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_connectionFailureType_r10_20 = {
	"connectionFailureType-r10",
	"connectionFailureType-r10",
	&asn_OP_NativeEnumerated,
	asn_DEF_connectionFailureType_r10_tags_20,
	sizeof(asn_DEF_connectionFailureType_r10_tags_20)
		/sizeof(asn_DEF_connectionFailureType_r10_tags_20[0]) - 1, /* 1 */
	asn_DEF_connectionFailureType_r10_tags_20,	/* Same as above */
	sizeof(asn_DEF_connectionFailureType_r10_tags_20)
		/sizeof(asn_DEF_connectionFailureType_r10_tags_20[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_connectionFailureType_r10_constr_20,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_connectionFailureType_r10_specs_20	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ext1_11[] = {
	{ ATF_POINTER, 6, offsetof(struct RLF_Report_r9__ext1, locationInfo_r10),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocationInfo_r10,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"locationInfo-r10"
		},
	{ ATF_POINTER, 5, offsetof(struct RLF_Report_r9__ext1, failedPCellId_r10),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_failedPCellId_r10_13,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"failedPCellId-r10"
		},
	{ ATF_POINTER, 4, offsetof(struct RLF_Report_r9__ext1, reestablishmentCellId_r10),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdEUTRA,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"reestablishmentCellId-r10"
		},
	{ ATF_POINTER, 3, offsetof(struct RLF_Report_r9__ext1, timeConnFailure_r10),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_timeConnFailure_r10_constr_19,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_timeConnFailure_r10_constraint_11
		},
		0, 0, /* No default value */
		"timeConnFailure-r10"
		},
	{ ATF_POINTER, 2, offsetof(struct RLF_Report_r9__ext1, connectionFailureType_r10),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_connectionFailureType_r10_20,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"connectionFailureType-r10"
		},
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9__ext1, previousPCellId_r10),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdEUTRA,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"previousPCellId-r10"
		},
};
static const int asn_MAP_ext1_oms_11[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_ext1_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ext1_tag2el_11[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* locationInfo-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* failedPCellId-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* reestablishmentCellId-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* timeConnFailure-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* connectionFailureType-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* previousPCellId-r10 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ext1_specs_11 = {
	sizeof(struct RLF_Report_r9__ext1),
	offsetof(struct RLF_Report_r9__ext1, _asn_ctx),
	asn_MAP_ext1_tag2el_11,
	6,	/* Count of tags in the map */
	asn_MAP_ext1_oms_11,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ext1_11 = {
	"ext1",
	"ext1",
	&asn_OP_SEQUENCE,
	asn_DEF_ext1_tags_11,
	sizeof(asn_DEF_ext1_tags_11)
		/sizeof(asn_DEF_ext1_tags_11[0]) - 1, /* 1 */
	asn_DEF_ext1_tags_11,	/* Same as above */
	sizeof(asn_DEF_ext1_tags_11)
		/sizeof(asn_DEF_ext1_tags_11[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ext1_11,
	6,	/* Elements count */
	&asn_SPC_ext1_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_failedPCellId_v1090_25[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext2__failedPCellId_v1090, carrierFreq_v1090),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueEUTRA_v9e0,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"carrierFreq-v1090"
		},
};
static const ber_tlv_tag_t asn_DEF_failedPCellId_v1090_tags_25[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_failedPCellId_v1090_tag2el_25[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* carrierFreq-v1090 */
};
static asn_SEQUENCE_specifics_t asn_SPC_failedPCellId_v1090_specs_25 = {
	sizeof(struct RLF_Report_r9__ext2__failedPCellId_v1090),
	offsetof(struct RLF_Report_r9__ext2__failedPCellId_v1090, _asn_ctx),
	asn_MAP_failedPCellId_v1090_tag2el_25,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_failedPCellId_v1090_25 = {
	"failedPCellId-v1090",
	"failedPCellId-v1090",
	&asn_OP_SEQUENCE,
	asn_DEF_failedPCellId_v1090_tags_25,
	sizeof(asn_DEF_failedPCellId_v1090_tags_25)
		/sizeof(asn_DEF_failedPCellId_v1090_tags_25[0]) - 1, /* 1 */
	asn_DEF_failedPCellId_v1090_tags_25,	/* Same as above */
	sizeof(asn_DEF_failedPCellId_v1090_tags_25)
		/sizeof(asn_DEF_failedPCellId_v1090_tags_25[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_failedPCellId_v1090_25,
	1,	/* Elements count */
	&asn_SPC_failedPCellId_v1090_specs_25	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ext2_24[] = {
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9__ext2, failedPCellId_v1090),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_failedPCellId_v1090_25,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"failedPCellId-v1090"
		},
};
static const int asn_MAP_ext2_oms_24[] = { 0 };
static const ber_tlv_tag_t asn_DEF_ext2_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ext2_tag2el_24[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* failedPCellId-v1090 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ext2_specs_24 = {
	sizeof(struct RLF_Report_r9__ext2),
	offsetof(struct RLF_Report_r9__ext2, _asn_ctx),
	asn_MAP_ext2_tag2el_24,
	1,	/* Count of tags in the map */
	asn_MAP_ext2_oms_24,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ext2_24 = {
	"ext2",
	"ext2",
	&asn_OP_SEQUENCE,
	asn_DEF_ext2_tags_24,
	sizeof(asn_DEF_ext2_tags_24)
		/sizeof(asn_DEF_ext2_tags_24[0]) - 1, /* 1 */
	asn_DEF_ext2_tags_24,	/* Same as above */
	sizeof(asn_DEF_ext2_tags_24)
		/sizeof(asn_DEF_ext2_tags_24[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ext2_24,
	1,	/* Elements count */
	&asn_SPC_ext2_specs_24	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_rlf_Cause_r11_value2enum_30[] = {
	{ 0,	11,	"t310-Expiry" },
	{ 1,	19,	"randomAccessProblem" },
	{ 2,	14,	"rlc-MaxNumRetx" },
	{ 3,	6,	"spare1" }
};
static const unsigned int asn_MAP_rlf_Cause_r11_enum2value_30[] = {
	1,	/* randomAccessProblem(1) */
	2,	/* rlc-MaxNumRetx(2) */
	3,	/* spare1(3) */
	0	/* t310-Expiry(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_rlf_Cause_r11_specs_30 = {
	asn_MAP_rlf_Cause_r11_value2enum_30,	/* "tag" => N; sorted by tag */
	asn_MAP_rlf_Cause_r11_enum2value_30,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_rlf_Cause_r11_tags_30[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rlf_Cause_r11_30 = {
	"rlf-Cause-r11",
	"rlf-Cause-r11",
	&asn_OP_NativeEnumerated,
	asn_DEF_rlf_Cause_r11_tags_30,
	sizeof(asn_DEF_rlf_Cause_r11_tags_30)
		/sizeof(asn_DEF_rlf_Cause_r11_tags_30[0]) - 1, /* 1 */
	asn_DEF_rlf_Cause_r11_tags_30,	/* Same as above */
	sizeof(asn_DEF_rlf_Cause_r11_tags_30)
		/sizeof(asn_DEF_rlf_Cause_r11_tags_30[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_rlf_Cause_r11_constr_30,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_rlf_Cause_r11_specs_30	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_basicFields_r11_28[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__basicFields_r11, c_RNTI_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_C_RNTI,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"c-RNTI-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__basicFields_r11, rlf_Cause_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_rlf_Cause_r11_30,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"rlf-Cause-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__basicFields_r11, timeSinceFailure_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeSinceFailure_r11,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"timeSinceFailure-r11"
		},
};
static const ber_tlv_tag_t asn_DEF_basicFields_r11_tags_28[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_basicFields_r11_tag2el_28[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* c-RNTI-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rlf-Cause-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* timeSinceFailure-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_basicFields_r11_specs_28 = {
	sizeof(struct RLF_Report_r9__ext3__basicFields_r11),
	offsetof(struct RLF_Report_r9__ext3__basicFields_r11, _asn_ctx),
	asn_MAP_basicFields_r11_tag2el_28,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_basicFields_r11_28 = {
	"basicFields-r11",
	"basicFields-r11",
	&asn_OP_SEQUENCE,
	asn_DEF_basicFields_r11_tags_28,
	sizeof(asn_DEF_basicFields_r11_tags_28)
		/sizeof(asn_DEF_basicFields_r11_tags_28[0]) - 1, /* 1 */
	asn_DEF_basicFields_r11_tags_28,	/* Same as above */
	sizeof(asn_DEF_basicFields_r11_tags_28)
		/sizeof(asn_DEF_basicFields_r11_tags_28[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_basicFields_r11_28,
	3,	/* Elements count */
	&asn_SPC_basicFields_r11_specs_28	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_physCellId_r11_38[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__previousUTRA_CellId_r11__physCellId_r11, choice.fdd_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellIdUTRA_FDD,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"fdd-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__previousUTRA_CellId_r11__physCellId_r11, choice.tdd_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellIdUTRA_TDD,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tdd-r11"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_physCellId_r11_tag2el_38[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd-r11 */
};
static asn_CHOICE_specifics_t asn_SPC_physCellId_r11_specs_38 = {
	sizeof(struct RLF_Report_r9__ext3__previousUTRA_CellId_r11__physCellId_r11),
	offsetof(struct RLF_Report_r9__ext3__previousUTRA_CellId_r11__physCellId_r11, _asn_ctx),
	offsetof(struct RLF_Report_r9__ext3__previousUTRA_CellId_r11__physCellId_r11, present),
	sizeof(((struct RLF_Report_r9__ext3__previousUTRA_CellId_r11__physCellId_r11 *)0)->present),
	asn_MAP_physCellId_r11_tag2el_38,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_physCellId_r11_38 = {
	"physCellId-r11",
	"physCellId-r11",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_physCellId_r11_constr_38,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_physCellId_r11_38,
	2,	/* Elements count */
	&asn_SPC_physCellId_r11_specs_38	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_previousUTRA_CellId_r11_36[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__previousUTRA_CellId_r11, carrierFreq_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueUTRA,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"carrierFreq-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__previousUTRA_CellId_r11, physCellId_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_physCellId_r11_38,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"physCellId-r11"
		},
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9__ext3__previousUTRA_CellId_r11, cellGlobalId_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdUTRA,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"cellGlobalId-r11"
		},
};
static const int asn_MAP_previousUTRA_CellId_r11_oms_36[] = { 2 };
static const ber_tlv_tag_t asn_DEF_previousUTRA_CellId_r11_tags_36[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_previousUTRA_CellId_r11_tag2el_36[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* carrierFreq-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* physCellId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* cellGlobalId-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_previousUTRA_CellId_r11_specs_36 = {
	sizeof(struct RLF_Report_r9__ext3__previousUTRA_CellId_r11),
	offsetof(struct RLF_Report_r9__ext3__previousUTRA_CellId_r11, _asn_ctx),
	asn_MAP_previousUTRA_CellId_r11_tag2el_36,
	3,	/* Count of tags in the map */
	asn_MAP_previousUTRA_CellId_r11_oms_36,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_previousUTRA_CellId_r11_36 = {
	"previousUTRA-CellId-r11",
	"previousUTRA-CellId-r11",
	&asn_OP_SEQUENCE,
	asn_DEF_previousUTRA_CellId_r11_tags_36,
	sizeof(asn_DEF_previousUTRA_CellId_r11_tags_36)
		/sizeof(asn_DEF_previousUTRA_CellId_r11_tags_36[0]) - 1, /* 1 */
	asn_DEF_previousUTRA_CellId_r11_tags_36,	/* Same as above */
	sizeof(asn_DEF_previousUTRA_CellId_r11_tags_36)
		/sizeof(asn_DEF_previousUTRA_CellId_r11_tags_36[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_previousUTRA_CellId_r11_36,
	3,	/* Elements count */
	&asn_SPC_previousUTRA_CellId_r11_specs_36	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_physCellId_r11_44[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__selectedUTRA_CellId_r11__physCellId_r11, choice.fdd_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellIdUTRA_FDD,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"fdd-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__selectedUTRA_CellId_r11__physCellId_r11, choice.tdd_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellIdUTRA_TDD,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tdd-r11"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_physCellId_r11_tag2el_44[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd-r11 */
};
static asn_CHOICE_specifics_t asn_SPC_physCellId_r11_specs_44 = {
	sizeof(struct RLF_Report_r9__ext3__selectedUTRA_CellId_r11__physCellId_r11),
	offsetof(struct RLF_Report_r9__ext3__selectedUTRA_CellId_r11__physCellId_r11, _asn_ctx),
	offsetof(struct RLF_Report_r9__ext3__selectedUTRA_CellId_r11__physCellId_r11, present),
	sizeof(((struct RLF_Report_r9__ext3__selectedUTRA_CellId_r11__physCellId_r11 *)0)->present),
	asn_MAP_physCellId_r11_tag2el_44,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_physCellId_r11_44 = {
	"physCellId-r11",
	"physCellId-r11",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_physCellId_r11_constr_44,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_physCellId_r11_44,
	2,	/* Elements count */
	&asn_SPC_physCellId_r11_specs_44	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_selectedUTRA_CellId_r11_42[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__selectedUTRA_CellId_r11, carrierFreq_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueUTRA,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"carrierFreq-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__ext3__selectedUTRA_CellId_r11, physCellId_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_physCellId_r11_44,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"physCellId-r11"
		},
};
static const ber_tlv_tag_t asn_DEF_selectedUTRA_CellId_r11_tags_42[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_selectedUTRA_CellId_r11_tag2el_42[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* carrierFreq-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* physCellId-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_selectedUTRA_CellId_r11_specs_42 = {
	sizeof(struct RLF_Report_r9__ext3__selectedUTRA_CellId_r11),
	offsetof(struct RLF_Report_r9__ext3__selectedUTRA_CellId_r11, _asn_ctx),
	asn_MAP_selectedUTRA_CellId_r11_tag2el_42,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_selectedUTRA_CellId_r11_42 = {
	"selectedUTRA-CellId-r11",
	"selectedUTRA-CellId-r11",
	&asn_OP_SEQUENCE,
	asn_DEF_selectedUTRA_CellId_r11_tags_42,
	sizeof(asn_DEF_selectedUTRA_CellId_r11_tags_42)
		/sizeof(asn_DEF_selectedUTRA_CellId_r11_tags_42[0]) - 1, /* 1 */
	asn_DEF_selectedUTRA_CellId_r11_tags_42,	/* Same as above */
	sizeof(asn_DEF_selectedUTRA_CellId_r11_tags_42)
		/sizeof(asn_DEF_selectedUTRA_CellId_r11_tags_42[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_selectedUTRA_CellId_r11_42,
	2,	/* Elements count */
	&asn_SPC_selectedUTRA_CellId_r11_specs_42	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ext3_27[] = {
	{ ATF_POINTER, 3, offsetof(struct RLF_Report_r9__ext3, basicFields_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_basicFields_r11_28,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"basicFields-r11"
		},
	{ ATF_POINTER, 2, offsetof(struct RLF_Report_r9__ext3, previousUTRA_CellId_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_previousUTRA_CellId_r11_36,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"previousUTRA-CellId-r11"
		},
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9__ext3, selectedUTRA_CellId_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_selectedUTRA_CellId_r11_42,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"selectedUTRA-CellId-r11"
		},
};
static const int asn_MAP_ext3_oms_27[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_ext3_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ext3_tag2el_27[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* basicFields-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* previousUTRA-CellId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* selectedUTRA-CellId-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ext3_specs_27 = {
	sizeof(struct RLF_Report_r9__ext3),
	offsetof(struct RLF_Report_r9__ext3, _asn_ctx),
	asn_MAP_ext3_tag2el_27,
	3,	/* Count of tags in the map */
	asn_MAP_ext3_oms_27,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ext3_27 = {
	"ext3",
	"ext3",
	&asn_OP_SEQUENCE,
	asn_DEF_ext3_tags_27,
	sizeof(asn_DEF_ext3_tags_27)
		/sizeof(asn_DEF_ext3_tags_27[0]) - 1, /* 1 */
	asn_DEF_ext3_tags_27,	/* Same as above */
	sizeof(asn_DEF_ext3_tags_27)
		/sizeof(asn_DEF_ext3_tags_27[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ext3_27,
	3,	/* Elements count */
	&asn_SPC_ext3_specs_27	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RLF_Report_r9_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9, measResultLastServCell_r9),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_measResultLastServCell_r9_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"measResultLastServCell-r9"
		},
	{ ATF_POINTER, 4, offsetof(struct RLF_Report_r9, measResultNeighCells_r9),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_measResultNeighCells_r9_5,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"measResultNeighCells-r9"
		},
	{ ATF_POINTER, 3, offsetof(struct RLF_Report_r9, ext1),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ext1_11,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ext1"
		},
	{ ATF_POINTER, 2, offsetof(struct RLF_Report_r9, ext2),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_ext2_24,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ext2"
		},
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9, ext3),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_ext3_27,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ext3"
		},
};
static const int asn_MAP_RLF_Report_r9_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_RLF_Report_r9_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RLF_Report_r9_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measResultLastServCell-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measResultNeighCells-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ext1 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ext2 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ext3 */
};
asn_SEQUENCE_specifics_t asn_SPC_RLF_Report_r9_specs_1 = {
	sizeof(struct RLF_Report_r9),
	offsetof(struct RLF_Report_r9, _asn_ctx),
	asn_MAP_RLF_Report_r9_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_RLF_Report_r9_oms_1,	/* Optional members */
	1, 3,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RLF_Report_r9 = {
	"RLF-Report-r9",
	"RLF-Report-r9",
	&asn_OP_SEQUENCE,
	asn_DEF_RLF_Report_r9_tags_1,
	sizeof(asn_DEF_RLF_Report_r9_tags_1)
		/sizeof(asn_DEF_RLF_Report_r9_tags_1[0]), /* 1 */
	asn_DEF_RLF_Report_r9_tags_1,	/* Same as above */
	sizeof(asn_DEF_RLF_Report_r9_tags_1)
		/sizeof(asn_DEF_RLF_Report_r9_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RLF_Report_r9_1,
	5,	/* Elements count */
	&asn_SPC_RLF_Report_r9_specs_1	/* Additional specs */
};

